#!/run/current-system/sw/bin/bash

# To enable custom, git-tracked hooks:
# git config -f .gitconfig core.hooksPath .githooks
# git config --local include.path ../.gitconfig

./.githooks/statix.sh
./.githooks/local-flake-check.sh
