scrape_configs:
- job_name: node
  static_configs:
  - targets: [ '192.168.10.57:9100' ]
    labels:
      instance: netpi1
  - targets: [ '192.168.10.201:9100' ]
    labels:
      instance: netpi2
  - targets: [ '192.168.20.42:9100' ]
    labels:
      instance: printpi
  - targets: [ '192.168.10.137:9100' ]
    labels:
      instance: c137
  - targets: [ '192.168.10.120:9100' ]
    labels:
      instance: workbox
  - targets: [ '192.168.10.12:9100' ]
    labels:
      instance: borrowbox
  - targets: [ '100.114.203.99:9100' ]
    labels:
      instance: cloudbox

- job_name: smartctl
  static_configs:
  - targets: [ '192.168.10.137:9633' ]
    labels:
      instance: c137
  - targets: [ '192.168.10.120:9633' ]
    labels:
      instance: workbox
  - targets: [ '192.168.10.12:9633' ]
    labels:
      instance: borrowbox

- job_name: zfs
  static_configs:
  - targets: [ '192.168.10.137:9134' ]
    labels:
      instance: c137
  - targets: [ '192.168.10.120:9134' ]
    labels:
      instance: workbox
  - targets: [ '192.168.10.12:9134' ]
    labels:
      instance: borrowbox
