scrape_configs:
- job_name: hass
  scrape_interval: 60s
  metrics_path: /api/prometheus
  authorization:
    credentials: "@prom_token@"
  scheme: https
  static_configs:
    - targets: [ 'home.thurs.pw' ]

- job_name: node
  static_configs:
  - targets: [ 'netpi1.thurs.pw:9100' ]
    labels:
      instance: netpi1
  - targets: [ 'netpi2.thurs.pw:9100' ]
    labels:
      instance: netpi2
  - targets: [ 'printpi.thurs.pw:9100' ]
    labels:
      instance: printpi
  - targets: [ 'c137.thurs.pw:9100' ]
    labels:
      instance: c137
  - targets: [ 'workbox.thurs.pw:9100' ]
    labels:
      instance: workbox
  - targets: [ 'borrowbox.thurs.pw:9100' ]
    labels:
      instance: borrowbox
  - targets: [ '100.114.203.99:9100' ]
    labels:
      instance: cloudbox

- job_name: smartctl
  static_configs:
  - targets: [ 'c137.thurs.pw:9633' ]
    labels:
      instance: c137
  - targets: [ 'workbox.thurs.pw:9633' ]
    labels:
      instance: workbox
  - targets: [ 'borrowbox.thurs.pw:9633' ]
    labels:
      instance: borrowbox

- job_name: zfs
  static_configs:
  - targets: [ 'c137.thurs.pw:9134' ]
    labels:
      instance: c137
  - targets: [ 'workbox.thurs.pw:9134' ]
    labels:
      instance: workbox
  - targets: [ 'borrowbox.thurs.pw:9134' ]
    labels:
      instance: borrowbox

- job_name: blocky
  scheme: https
  static_configs:
  - targets: [ 'blocky.netpi1.thurs.pw' ]
    labels:
      instance: netpi1
  - targets: [ 'blocky.netpi2.thurs.pw' ]
    labels:
      instance: netpi2
  - targets: [ 'blocky.homebox.thurs.pw' ]
    labels:
      instance: homebox

