http:
  routers:
    loki:
      rule: "Host(`loki.thurs.pw`)"
      service: loki
      entrypoints:
        - "websecure"
      tls:
        certResolver: letsencrypt

  services:
    loki:
      loadBalancer:
        servers:
        - url: http://192.168.10.68:3100
