default:
  tags:
    - wormhole

stages:
  - flake

flake:update:
  stage: flake
  image: local/nix-daemon:latest
  before_script:
  - . "$HOME/.nix-profile/etc/profile.d/nix.sh"
  script:
    - nix --version
    - NIX_CONFIG="access-tokens = github.com=$GITHUB_PAT" nix flake update
    - /bin/attic login local http://192.168.10.15:8080 $ATTIC_TOKEN
    - nix build .#nixosConfigurations.homebox.config.system.build.toplevel
    - /bin/attic push local ./result && rm -fv ./result
    - nix build .#nixosConfigurations.c137.config.system.build.toplevel
    - /bin/attic push local ./result && rm -fv ./result

