default:
  tags:
    - wormhole

stages:
  - flake

flake:update:
  stage: flake
  image: local/nix-daemon:latest
  before_script:
  - . "$HOME/.nix-profile/etc/profile.d/nix.sh"
  script:
    - nix --version
    - NIX_CONFIG="access-tokens = github.com=$GITHUB_PAT" nix flake update
    - nix build .#nixosConfigurations.c137.config.system.build.toplevel
