apiVersion: 1

deleteDatasources:
  - name: kepler
    orgId: 1

datasources:
  - name: infra
    uid: cfs479kp23qpsb
    type: prometheus
    access: proxy
    url: http://192.168.10.68:8428
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.52.0

  - name: hass
    uid: cfs3ti9ys3xfkb
    type: prometheus
    access: proxy
    url: http://192.168.10.60:8428
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.52.0
