# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  ...
}:
{
  imports = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  boot = {
    kernelModules = [ ];
    extraModulePackages = [ ];
    initrd = {
      availableKernelModules = [ "nvme" ];
      kernelModules = [ ];
    };
  };

  swapDevices = [
    {
      device = "/swap";
    }
  ];
  fileSystems = {
    "/" = {
      device = "/dev/disk/by-label/nixos";
      fsType = "ext4";
    };
    "/opt/configs" = {
      device = "/dev/disk/by-label/configs";
      fsType = "ext4";
    };
  };

  networking.useDHCP = lib.mkDefault true;
}
