test_boolean:
  name: Dev testing
  initial: false
  icon: mdi:lock
lights_all:
  name: All Lights
  initial: true
  icon: mdi:ceiling-light
lock_front_door_jammed:
  name: Determine if front door lock is jammed
  icon: mdi:lock-alert
  initial: false
lock_back_door_jammed:
  name: Determine if back door lock is jammed
  icon: mdi:lock-alert
  initial: false
automated_locks:
  name: Use smart lock automations
  initial: true
  icon: mdi:lock
motion_all:
  name: All Motion Automations
  initial: true
  icon: mdi:run-fast
motion_office:
  name: Office Motion Automations
  initial: true
  icon: mdi:run-fast
motion_stairway:
  name: Stairway Motion Automations
  initial: true
  icon: mdi:run-fast
motion_kitchen:
  name: Kitchen Motion Automations
  initial: true
  icon: mdi:run-fast
motion_sim:
  name: Sim Motion Automations
  initial: true
  icon: mdi:run-fast
computer_c137:
  name: Desktop c137
  initial: false
  icon: mdi:desktop-classic
computer_sim:
  name: Desktop Sim
  initial: false
  icon: mdi:desktop-classic
computer_gamer:
  name: Desktop Gamer
  initial: false
  icon: mdi:desktop-classic
activity_sim:
  name: Sim Golf
  initial: false
  icon: mdi:golf
hvac_manual_control:
  name: HVAC Manual Control
  initial: false
  icon: mdi:thermostat
