_: {
  configurations.nixos.gcloudbox.module =
    # Do not modify this file!  It was generated by ‘nixos-generate-config’
    # and may be overwritten by future invocations.  Please make changes
    # to /etc/nixos/configuration.nix instead.
    {
      lib,
      ...
    }:
    {
      imports = [ ];

      boot = {
        kernelModules = [ ];
        extraModulePackages = [ ];
        initrd = {
          availableKernelModules = [ "nvme" ];
          kernelModules = [ ];
        };
      };

      swapDevices = [
        {
          device = "/swap";
          size = 2048;
        }
      ];

      fileSystems = {
        "/" = {
          device = "/dev/disk/by-label/nixos";
          fsType = "ext4";
        };
      };

      boot.loader.systemd-boot.configurationLimit = 5;

      networking.useDHCP = lib.mkDefault true;
      nixpkgs.hostPlatform = "x86_64-linux";
      system.stateVersion = "25.11";
    };
}
