http:
  routers:
    monitor:
      rule: "Host(`monitor.thurs.pw`)"
      service: monitor
      entrypoints:
        - "websecure"
      tls:
        certResolver: letsencrypt

  services:
    monitor:
      loadBalancer:
        servers:
        - url: http://192.168.10.68:8890
