http:
  routers:
    upsnap:
      rule: "Host(`upsnap.thurs.pw`)"
      service: upsnap
      entrypoints:
        - "websecure"
      tls:
        certResolver: letsencrypt

  services:
    upsnap:
      loadBalancer:
        servers:
        - url: http://192.168.10.15:8090
