http:
  routers:
    blocky:
      rule: "Host(`blocky.@host@.thurs.pw`)"
      service: blocky
      entrypoints:
        - "websecure"
      tls:
        certResolver: letsencrypt

  services:
    blocky:
      loadBalancer:
        servers:
        - url: http://@host@.thurs.pw:4000
