{ lib, config, ... }:
with lib;
with lib.thurs;
let

  cfg = config.mine.desktop.hyprpaper;
  user = config.mine.user;

in
{
  options.mine.desktop.hyprpaper = {
    home = mkEnableOption "Enable Hyprpaper Home-Manager config";
    settings = with types; {
      preload = mkOption {
        type = listOf path;
        default = [ ];
        description = ''
          Wallpaper images that should be preloaded into memory
        '';
        example = [ ./wallpapers/example.png ];
      };
      wallpapers = mkOption {
        type = listOf str;
        default = [ ];
        description = ''
          Wallpaper to monitor mapper
        '';
        example = [ "monitor,./wallpapers/example.png" ];
      };
    };
  };

  config = mkIf cfg.home {
    mine.desktop.hyprpaper.settings = {
      preload = [
        "/home/thurs/pictures/wallpapers/blue_astronaut_in_space.png"
        "/home/thurs/pictures/wallpapers/Kurzgesagt_Galaxies.png"
      ];
      wallpapers = [
        "DP-1,/home/thurs/pictures/wallpapers/Kurzgesagt_Galaxies.png"
        "DP-2,/home/thurs/pictures/wallpapers/blue_astronaut_in_space.png"
        "DP-3,/home/thurs/pictures/wallpapers/blue_astronaut_in_space.png"
      ];
    };

    home-manager.users.${user.name} = {
      xdg.configFile = {
        "hypr/hyprpaper.conf".text = ''
          # Auto-generated by Nix home-manager module

          # hyprpaper.settings.preload
          ${(lists.foldl (acc: v:
            acc + ''
              preload = ${v}
            '') "" cfg.settings.preload)}
          ${(lists.foldl (acc: v:
            acc + ''
              wallpaper = ${v}
              '') "" cfg.settings.wallpapers)}
        '';
      };
    };

  };
}
